process.env.NEXT_PUBLIC_APP_VERSION = require("./package.json").version;

/** @type {import('next').NextConfig} */

const CACHE_VERSION = "v3";

// Client code (the app-shell self-heal) writes into the same runtime caches
// the service worker reads from, so the version has to be visible to both.
process.env.NEXT_PUBLIC_SW_CACHE_VERSION = CACHE_VERSION;

// Single source of truth for the cache version inside the service worker:
// sw-version.js is generated here and loaded (via importScripts, before
// background-sync-sw.js) so the SW's activate-purge can never disagree with
// the cache names configured below. A hand-kept copy once diverged and the
// purge deleted the live app-shell caches.
require("fs").writeFileSync(
  require("path").join(__dirname, "public", "sw-version.js"),
  `// Generated by next.config.js — do not edit.\nself.__SW_CACHE_VERSION = ${JSON.stringify(CACHE_VERSION)};\n`,
);

// Every page in this app is a static client shell — the query string never
// changes the HTML or the RSC payload (tabs, edit ids etc. are read client
// side). Cache documents and payloads by pathname only, so `/add?tab=income`
// hits the cached `/add` instead of missing offline. Applies to both reads
// and writes, so each route has exactly one cache entry.
const stripSearchPlugin = {
  cacheKeyWillBeUsed: async ({ request }) => {
    const url = new URL(request.url);
    url.search = "";
    return url.toString();
  },
};

// Every page in this app is a static client shell, so every route's document
// can live in Workbox's *precache* — not merely a runtime cache that only
// fills when the user happens to visit the route while online. Precaching
// them all makes a cold offline launch work for any route immediately after
// install. `revision: null` is intentional: next-pwa's own manifest transform
// replaces it with the current Next build ID, so a new deploy installs fresh
// documents alongside their matching JS chunks.
const APP_SHELL_DOCUMENTS = [
  "/add",
  "/login",
  "/register",
  "/dashboard",
  "/settings",
  "/expenses",
  "/expenses/edit",
  "/income",
  "/income/edit",
  "/cards",
  "/loans",
  "/onboarding",
];
const appShellManifestTransform = async (manifest) => ({
  manifest: [
    ...manifest,
    ...APP_SHELL_DOCUMENTS.map((url) => ({ url, revision: null })),
  ],
  warnings: [],
});

const withPWA = require("next-pwa")({
  dest: "public",
  // Registration is owned exclusively by usePwaRegistration, which registers
  // with `updateViaCache: "none"`. next-pwa's injected auto-register script
  // raced it with the default updateViaCache and could win, silently
  // re-enabling the HTTP-cached-sw.js update flapping the hook exists to
  // prevent.
  register: false,
  // A new worker activates itself immediately. This must NOT be false: old
  // installs serve their own stale precached startup documents cache-first
  // even while online, so no new *page* code (toast, boot-promote) ever runs
  // on them — the only update path that reaches every device unconditionally
  // is the browser's sw.js re-fetch (served with max-age=0) followed by the
  // worker activating itself. With it false, real devices sat for months on
  // an ancient worker with a fully-installed successor stuck in waiting, and
  // offline cold start served the fallback page.
  skipWaiting: true,
  clientsClaim: true,
  disable: process.env.NODE_ENV === "development",
  sw: "sw.js",
  // Order matters: sw-version.js defines self.__SW_CACHE_VERSION before
  // background-sync-sw.js reads it.
  importScripts: ["/sw-version.js", "/background-sync-sw.js"],
  buildExcludes: [/app-build-manifest\.json$/, /middleware-manifest\.json$/],
  publicExcludes: [
    "!robots.txt",
    "!sitemap.xml",
    "!background-sync-sw.js",
    "!sw-version.js",
    // Cloudflare consumes these config files and serves 404 for their URLs.
    // Precaching them made the ENTIRE service-worker install fail atomically
    // (bad-precaching-response) on the Workers deployment — no SW could ever
    // install there, so the app had zero offline capability in production.
    "!_headers",
    "!_redirects",
  ],
  // dynamicStartUrl is off, so start_url ("/") is precached as a static
  // document. (dynamicStartUrlRedirect only applies when it is on.)
  dynamicStartUrl: false,
  // Match precached documents regardless of query string. The app itself
  // navigates to `/add?tab=income` and `/expenses/edit?id=…`; with the default
  // (ignore nothing) those URLs missed the precache and fell through to the
  // runtime NetworkFirst rules, whose caches never fill while online because
  // the plain paths are answered by the precache — so a cold offline start on
  // either URL showed the /offline fallback. Query strings never change these
  // static client shells, and no precached asset is keyed by one.
  ignoreURLParametersMatching: [/.*/],
  // Extends (rather than replaces) next-pwa's public/static asset manifest.
  // See the comment above `startupShellManifestTransform` for the revision
  // behavior. These pages contain no server-rendered user data.
  manifestTransforms: [appShellManifestTransform],
  fallbacks: {
    // Served for any offline navigation whose HTML is not cached. Must be a
    // real, static, auth-free page — falling back to "/" (a blank client-side
    // redirector) sent offline users into a white-screen loop.
    document: "/offline",
  },
  cacheOnFrontEndNav: true,
  reloadOnOnline: false,
  runtimeCaching: [
    {
      // Workbox matches RegExp routes against the full href for same-origin
      // requests, so a leading-slash pattern here never matched anything and
      // this rule was dead — chunks were only cached by the extension-based
      // rule below. Match on the pathname instead.
      urlPattern: ({ url, sameOrigin }) =>
        sameOrigin && url.pathname.startsWith("/_next/static/"),
      handler: "CacheFirst",
      options: {
        cacheName: `next-static-chunks-${CACHE_VERSION}`,
        expiration: {
          maxEntries: 200,
          maxAgeSeconds: 365 * 24 * 60 * 60,
        },
        cacheableResponse: {
          statuses: [0, 200],
        },
      },
    },
    {
      urlPattern: /\.(?:png|jpg|jpeg|svg|gif|ico|webp|avif)$/,
      handler: "CacheFirst",
      options: {
        cacheName: `images-${CACHE_VERSION}`,
        expiration: {
          maxEntries: 60,
          maxAgeSeconds: 30 * 24 * 60 * 60,
        },
      },
    },
    {
      urlPattern: /\.(?:js|css|woff|woff2|ttf|eot)$/,
      handler: "CacheFirst",
      options: {
        cacheName: `static-resources-${CACHE_VERSION}`,
        expiration: {
          maxEntries: 100,
          maxAgeSeconds: 30 * 24 * 60 * 60,
        },
      },
    },
    // Backend calls are never cached. Offline reads come from IndexedDB and
    // offline writes from the mutation queue; replaying a cached POST response
    // would make a mutation look like it succeeded when it never ran.
    {
      urlPattern: ({ url }) =>
        url.hostname.includes("convex") ||
        url.pathname.includes("/_convex/") ||
        url.pathname.includes("/api/"),
      handler: "NetworkOnly",
      options: {
        // next-pwa reads `options` while wiring up precache fallbacks, so the
        // key has to be present even when there is nothing to configure.
        plugins: [],
      },
    },
    // Documents and RSC payloads use NetworkFirst, NOT StaleWhileRevalidate:
    // serving a previous build's copy while online makes Next.js detect
    // version skew and force a full reload, which fetches the same stale copy
    // — a black-flash reload loop after every deploy. NetworkFirst means
    // online navigations always match the server's build; offline, the fetch
    // rejects immediately and the cache answers with no added latency. The
    // 3s timeout only matters on connections that hang (lie-fi).
    //
    // App Router client navigations fetch an RSC payload (`/route?_rsc=…`)
    // instead of a document, so the page rules below never see them. Handle
    // them deliberately: without this rule they fell into the general
    // CacheFirst bucket keyed by the varying `_rsc` token — stale for up to
    // 7 days online, and mostly cache misses offline.
    {
      urlPattern: ({ url, sameOrigin }) =>
        sameOrigin && url.searchParams.has("_rsc"),
      handler: "NetworkFirst",
      options: {
        cacheName: `rsc-${CACHE_VERSION}`,
        networkTimeoutSeconds: 3,
        expiration: {
          maxEntries: 50,
          maxAgeSeconds: 24 * 60 * 60,
        },
        cacheableResponse: {
          statuses: [0, 200],
        },
        // RSC responses carry a Vary header that would defeat cache.match.
        matchOptions: { ignoreVary: true },
        // Drops the whole query — including the varying `_rsc` token — so a
        // route has one payload entry that every navigation to it can hit.
        plugins: [stripSearchPlugin],
      },
    },
    {
      urlPattern: ({ request, url }) => {
        const pathname = new URL(url).pathname;
        const appPages = [
          "/dashboard",
          "/add",
          "/cards",
          "/settings",
          "/onboarding",
          "/loans",
          "/expenses",
          "/income",
        ];
        return (
          request.destination === "document" &&
          appPages.some((page) => pathname.startsWith(page))
        );
      },
      handler: "NetworkFirst",
      options: {
        cacheName: `app-pages-${CACHE_VERSION}`,
        networkTimeoutSeconds: 3,
        // Next.js documents ship `Vary: rsc, next-router-*, Accept-Encoding`,
        // and the Cache API honors Vary — an offline navigation's headers
        // never match the ones the entry was stored under, so every lookup
        // missed and fell through to the offline page. One HTML per route is
        // the intent here; Vary adds nothing but false misses.
        matchOptions: { ignoreVary: true },
        plugins: [stripSearchPlugin],
        expiration: {
          maxEntries: 30,
          maxAgeSeconds: 7 * 24 * 60 * 60,
        },
        cacheableResponse: {
          statuses: [0, 200],
        },
      },
    },
    {
      urlPattern: ({ request, url }) => {
        const pathname = new URL(url).pathname;
        return (
          request.destination === "document" &&
          (pathname === "/" ||
            pathname === "/login" ||
            pathname === "/register")
        );
      },
      handler: "NetworkFirst",
      options: {
        cacheName: `root-pages-${CACHE_VERSION}`,
        networkTimeoutSeconds: 3,
        // Next.js documents ship `Vary: rsc, next-router-*, Accept-Encoding`,
        // and the Cache API honors Vary — an offline navigation's headers
        // never match the ones the entry was stored under, so every lookup
        // missed and fell through to the offline page. One HTML per route is
        // the intent here; Vary adds nothing but false misses.
        matchOptions: { ignoreVary: true },
        plugins: [stripSearchPlugin],
        expiration: {
          maxEntries: 10,
          maxAgeSeconds: 14 * 24 * 60 * 60,
        },
        cacheableResponse: {
          statuses: [0, 200],
        },
      },
    },
    {
      urlPattern: ({ request }) => request.destination === "document",
      handler: "NetworkFirst",
      options: {
        cacheName: `pages-${CACHE_VERSION}`,
        networkTimeoutSeconds: 3,
        // Next.js documents ship `Vary: rsc, next-router-*, Accept-Encoding`,
        // and the Cache API honors Vary — an offline navigation's headers
        // never match the ones the entry was stored under, so every lookup
        // missed and fell through to the offline page. One HTML per route is
        // the intent here; Vary adds nothing but false misses.
        matchOptions: { ignoreVary: true },
        plugins: [stripSearchPlugin],
        expiration: {
          maxEntries: 50,
          maxAgeSeconds: 7 * 24 * 60 * 60,
        },
        cacheableResponse: {
          statuses: [0, 200],
        },
      },
    },
    {
      urlPattern: ({ url }) => {
        const pathname = new URL(url).pathname;
        return pathname.includes("/_vercel/");
      },
      handler: "NetworkOnly",
      options: {
        plugins: [
          {
            handlerDidError: async () => {
              console.log("Vercel analytics unavailable offline");
              return new Response("", { status: 200 });
            },
          },
        ],
      },
    },
    {
      urlPattern: ({ request, url }) => {
        const pathname = new URL(url).pathname;
        const noCache = [
          "/api/",
          "/_next/webpack-hmr",
          "/_vercel/",
          "/_next/static/",
          "/_convex/",
        ];
        if (noCache.some((route) => pathname.includes(route))) return false;
        if (request.destination === "document") return false;
        if (request.destination === "manifest") return false;
        // RSC payloads have their own rule above; belt-and-braces so they can
        // never land in a CacheFirst bucket again.
        if (new URL(url).searchParams.has("_rsc")) return false;
        return true;
      },
      handler: "CacheFirst",
      options: {
        cacheName: `general-cache-${CACHE_VERSION}`,
        expiration: {
          maxEntries: 100,
          maxAgeSeconds: 7 * 24 * 60 * 60,
        },
        cacheableResponse: {
          statuses: [0, 200],
        },
      },
    },
  ],
});

const path = require("path");

const nextConfig = {
  // ۱. اضافه شدن خروجی مستقل برای سازگاری حداکثری با کلودفلر
  output: "standalone",
  
  typescript: {
    ignoreBuildErrors: false,
  },
  experimental: {
    optimizePackageImports: ["lucide-react", "framer-motion"],
    outputFileTracingRoot: __dirname,
  },
  images: {
    formats: ["image/webp", "image/avif"],
    qualities: [75, 100],
    deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048, 3840],
    imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
  },
  async headers() {
    return [
      {
        source: "/:path*",
        headers: [
          // Clickjacking: the app has no legitimate reason to be framed.
          { key: "X-Frame-Options", value: "DENY" },
          { key: "X-Content-Type-Options", value: "nosniff" },
          // Keeps paths (and anything in a query string) out of Referer
          // headers sent to third parties.
          { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
          {
            key: "Permissions-Policy",
            value: "camera=(), microphone=(), geolocation=(), interest-cohort=()",
          },
          {
            key: "Strict-Transport-Security",
            value: "max-age=63072000; includeSubDomains; preload",
          },
          // CSP is shipped in Report-Only first: Next.js injects inline
          // bootstrap scripts and the app uses inline styles, so a blocking
          // policy needs the hash/nonce work done and verified before it is
          // safe to enforce. Watch the browser console for violations, then
          // switch this key to `Content-Security-Policy`.
          {
            key: "Content-Security-Policy-Report-Only",
            value: [
              "default-src 'self'",
              "script-src 'self' 'unsafe-inline' 'unsafe-eval'",
              "style-src 'self' 'unsafe-inline'",
              "img-src 'self' data: blob:",
              "font-src 'self' data:",
              // Convex realtime uses both HTTPS and WebSockets.
              "connect-src 'self' https://*.convex.cloud wss://*.convex.cloud https://*.convex.site",
              "worker-src 'self'",
              "manifest-src 'self'",
              "object-src 'none'",
              "base-uri 'self'",
              "form-action 'self'",
              "frame-ancestors 'none'",
            ].join("; "),
          },
        ],
      },
    ];
  },
  webpack: (config, { isServer }) => {
    config.resolve.alias = {
      ...config.resolve.alias,
      "@": path.join(__dirname, "src"),
    };

    if (!isServer) {
      config.resolve.fallback = {
        ...config.resolve.fallback,
        fs: false,
      };
    }

    // ۲. اصلاح وب‌پک: حذف چانک‌بندی دستی زمان بیلد سرور برای جلوگیری از تداخل با وورکرها
    if (!isServer) {
      config.optimization = {
        ...config.optimization,
        splitChunks: {
          chunks: "all",
          cacheGroups: {
            vendor: {
              test: /[\/]node_modules[\/]/,
              name: "vendors",
              chunks: "all",
            },
            common: {
              name: "common",
              minChunks: 2,
              chunks: "all",
              enforce: true,
            },
          },
        },
      };
    }

    return config;
  },
  compress: true,
};

module.exports = withPWA(nextConfig);
